export const cartActionTypes = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    REOMVE_ITEM: "REOMVE_ITEM",
    CLEAR_ITEM: "CLEAR_ITEM",
    CLEAR_CART: "CLEAR_CART",
};
